name: ds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pandas
  - polars
  - pyarrow
  - fastparquet
  - scikit-learn
  - plotly
  - seaborn
  - pip:
    - torch
    - wandb
    - python-dotenv
